- hosts: 3.6.40.140
  vars:
          network_ip: "10.240.0.0/16"

  tasks:
          - name: "installing docker"
            package:
                    name: "docker"
                    state: present

          - name: "changing the driver of docker to systemd"
            copy:
                    dest: /etc/docker/daemon.json
                    content: " { \"exec-opts\":[\"native.cgroupdriver=systemd\"] }"                  
          - name: "starting and enabling docker"
            service:
                    name: docker
                    state: started
                    enabled: yes

          - name: "configuring yum repo for kubeadm,kubelet & kubectl"
            yum_repository:
                    name: "kubernetes"
                    description: "repo for kubernetes"
                    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
                    enabled: yes
                    repo_gpgcheck: yes
                    gpgcheck: yes
                    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
                    exclude:
                            - kubelet
                            - kubeadm
                            - kubectl
                            
          - name: "installing kubeadm,kubelet & kubectl"
            yum:
                    name: ["kubeadm ","kubelet","kubectl"]
                    disable_excludes: "kubernetes"
                    state: present

          - name: "starting and enabling kubelet service"
            service:
                    enabled: yes
                    name: "kubelet"
                    state: started

          - name: "pulling config images"
            shell:
                    cmd: "kubeadm config images pull"

          - name: "installing iproute-tc"
            package: 
                    name: "iproute-tc"
                    state: present

          - name: "change the value bridge-nf-call-iptables"
            lineinfile:
                    path: /proc/sys/net/bridge/bridge-nf-call-iptables
                    line: "1"
                    state: present
  
          - name: "copying flannel-cfg file"
            template:
                    src: /flannel-cfg/flannel.yml
                    dest: /root/flannel.yml
          
          - name: "initializing kubeadm and config master as a client"
            shell:
                    cmd: "{{ item }}"
                    chdir: /root
            with_items:
                    - "kubeadm init --pod-network-cidr={{ network_ip }} --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
                    - "mkdir -p $HOME/.kube"
                    - "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
                    - "sudo chown $(id -u):$(id -g) $HOME/.kube/config"
                    - "kubectl apply -f flannel.yml"
 

          - name: "storing token value"
            shell:
                    cmd: "kubeadm token create --print-join-command > /root/token.py"
 

          - name: "fetch the token value file from masterhost to localhost"
            fetch:
                    src: /root/token.py
                    dest: /token/
                    flat: yes

