- hosts: localhost

  tasks:
          - name: "installing docker"
            package:
                    name: "docker"
                    state: present

          - name: "changing the driver od docker to systemd"
            copy:
                    dest: <F2>etc<F2>docker<F2>daemon.json
                    content: |
                    {
                            "exec-opts":["native.cgroupdriver=systemd"]
                    }

          - name: "starting and enabling docker"
            service:
                    enabled: yes
                    name: docker
                    state: started

          - name: "configuring yum repo for kubeadm, kubelet & kubectl"
            yum_repository:
                    name: "kubernetes"
                    description: "repo for kubernetes"
                    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
                    enabled: yes
                    repo_gpgcheck: yes
                    gpgcheck: yes
                    gpgkey:
                            -  "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
                            -  "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
  

          - name: "installing kubeadm,kubelet & kubectl"
            yum:
                    name: ["kubeadm","kubelet","kubectl"]
                    disable_excludes: "kubernetes"
                    state: present

          - name: "starting and enabling kubelet service"
            service:
                    enabled: yes
                    name: "kubelet"
                    state: started

          - name: "pulling config images"
            shell:
                    cmd: "kubeadm config images pull"

          - name: "installing iproute-tc"
            package:
                    name: "iproute-tc"
                    state: present

          - name: "config kubernetes config file"
            copy:
                    dest: "/etc/sysctl.d/k8s.conf"
                    content: |
           net.bridge.bridge-nf-call-ip6tables=1
           net.bridge.bridge-nf-call-iptables=1
 
          - name: "restart system"
            shell:
                    cmd: "sysctl --system"
  
          - name: "copy token file from local host to slave host"
            copy:
                    src: /token/token.py
                    dest: /etc/
  
          - name: "converting token file to execution mode and then execute it"
            shell:
                    cmd: "{{ item }}"
                    chdir: /etc/
            with_items:
                    - "chmod +x token.py"
                    - "./token.py"
